"""create chat table

Revision ID: 3937c851e848
Revises: 9f0e98cad060
Create Date: 2025-03-26 20:03:38.137858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3937c851e848'
down_revision = '9f0e98cad060'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
