"""create chat and ai table

Revision ID: 8c1a2d1d7aa1
Revises: 3937c851e848
Create Date: 2025-03-26 20:36:07.633580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1a2d1d7aa1'
down_revision = '3937c851e848'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
