"""additional changes

Revision ID: 9f0e98cad060
Revises: d9023870f68a
Create Date: 2025-03-26 19:10:39.200981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0e98cad060'
down_revision = 'd9023870f68a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
